services:
  
  app:
    build:
      context: ..
      dockerfile: infra/app/Dockerfile

    container_name: pets_app

    user: "${UID}:${GID}"

    working_dir: /app

    volumes:
      - ../app:/app

    ports:
      - "8080:8080"

    depends_on:
      - db

    tty: true

    stdin_open: true
  db:
    image: postgres:16

    container_name: pets_db

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql